### ISSUE TITLE
The workflow is not valid:  Unexpected value 'args'" args.

### ISSUE THREAD

**Issue by brpaz** [Roang-zero1/github-upload-release-artifacts-action#3]
Hello.
I have tried to use your action, but GitHub says the workflow is not valid: "The workflow is not valid. .github/workflows/publish-plugin.yml (Line: 29, Col: 9): Unexpected value 'args'" args.

Here is my example:

```
      - name: Push Artifact to release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          created_tag: ${{ github.ref }}
          args:
             - build/distributions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I have checked the source and "args" are indeed not defined as an input for the plugin.
