### ISSUE TITLE
Wildcard support in args would be nice

### ISSUE THREAD

**Issue by mgerhardy** [Roang-zero1/github-upload-release-artifacts-action#6]
Being able to specify wildcards would be really useful

```yaml
        - name: Upload the ubuntu release artifacts
          if: startsWith(github.ref, 'refs/tags/')
          uses: Roang-zero1/github-upload-release-artifacts-action@v1
          with:
            args: vengi*.deb
```

but doing so produces:

```
Error: Invalid path passed: vengi*.deb
```
