### ISSUE TITLE
This is not a tagged push after github-create-release-action with created_tag

### ISSUE THREAD

**Issue by kitingChris** [Roang-zero1/github-upload-release-artifacts-action#7]
I get an error when using github-create-release-action with created_tag
```
name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build debian package
        run: ./create-deb.sh

      - name: Get version
        run: |
          version=$(ls azure-storage-explorer_*_x64.deb | grep -Po '(?<=azure-storage-explorer_)[^\_]+')
          echo "version=$version" >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ env.version }}',
              sha: context.sha
            })
          
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          created_tag: 'v${{ env.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "azure-storage-explorer_${{ env.version }}_x64.deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

```
Run Roang-zero1/github-upload-release-artifacts-action@v2
/usr/bin/docker run --name c044253b6ea2b480[7](https://github.com/kitingChris/azure-storage-explorer-deb-package/actions/runs/4450203117/jobs/7815362068#step:9:8)453d94b1[8](https://github.com/kitingChris/azure-storage-explorer-deb-package/actions/runs/4450203117/jobs/7815362068#step:9:9)35f47b1a63a_8c7e5a --label 6c0442 --workdir /github/workspace --rm -e "version" -e "GITHUB_TOKEN" -e "INPUT_ARGS" -e "INPUT_CREATED_TAG" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/azure-storage-explorer-deb-package/azure-storage-explorer-deb-package":"/github/workspace" 6c0442:53b6ea2b4807453d94b1835f47b1a63a azure-storage-explorer_1.1.1_x64.deb
This is not a tagged push.
```
